import React, { createContext, useContext, useState, useEffect } from 'react';

export type ThemeFamily =
  | 'red'
  | 'orange'
  | 'yellow'
  | 'green'
  | 'teal'
  | 'blue'
  | 'indigo'
  | 'purple'
  | 'rose'
  | 'earth'
  | 'neutral';

export type ThemeMode =
  // Red
  | 'ruby_light'
  | 'ruby_dark'
  // Orange
  | 'amber_light'
  | 'amber_dark'
  // Yellow
  | 'gold_light'
  | 'gold_dark'
  // Green
  | 'sage_light'
  | 'sage_dark'
  // Teal
  | 'teal_light'
  | 'teal_dark'
  // Blue
  | 'mist'
  | 'deep_sea'
  // Indigo
  | 'indigo_light'
  | 'indigo_dark'
  // Purple
  | 'lavender_light'
  | 'lavender_dark'
  // Rose
  | 'rose_light'
  | 'rose_dark'
  // Earth
  | 'linen'
  | 'earth_dark'
  // Neutral
  | 'slate_light'
  | 'dusk';

export interface ThemePalette {
  id: ThemeMode;
  name: string;
  family: ThemeFamily;
  familyName: string;
  variant: 'light' | 'dark';
  icon: string;
  swatchCanvas: string;
  swatchCard: string;
  swatchAccent: string;
  subtitle: string;
  canvas: string;
  topBar: string;
  topBarBorder: string;
  card: string;
  cardBorder: string;
  cardShadow: string;
  inputBg: string;
  inputBorder: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  accentPrimary: string;
  accentHover: string;
  accentText: string;
  badgeBg: string;
  badgeBorder: string;
  badgeText: string;
  affirmationBg: string;
  affirmationBorder: string;
  affirmationText: string;
  affirmationLabel: string;
  quoteBg: string;
  quoteBorder: string;
  quoteText: string;
  quoteLabel: string;
  practiceBg: string;
  practiceBorder: string;
  modalOverlay: string;
  crisisBg: string;
  crisisBorder: string;
  crisisText: string;
  crisisAccent: string;
  tabActiveBg: string;
  tabActiveText: string;
  tabInactiveBg: string;
  tabInactiveText: string;
}

export const THEMES: Record<ThemeMode, ThemePalette> = {
  // ==========================================
  // 1. RED & CRIMSON SPECTRUM
  // ==========================================
  ruby_light: {
    id: 'ruby_light',
    name: 'Ruby Dawn',
    family: 'red',
    familyName: 'Red & Crimson',
    variant: 'light',
    icon: '🔴',
    swatchCanvas: '#FFF5F6',
    swatchCard: '#FFFFFF',
    swatchAccent: '#E11D48',
    subtitle: 'Vivid jewel ruby & crisp coral blush',
    canvas: '#FFF5F6',
    topBar: '#FFFFFF',
    topBarBorder: '#FECDD3',
    card: '#FFFFFF',
    cardBorder: '#FFE4E6',
    cardShadow: 'rgba(225, 29, 72, 0.14)',
    inputBg: '#FFF1F2',
    inputBorder: '#FECDD3',
    textPrimary: '#1E060B',
    textSecondary: '#6A1A2B',
    textMuted: '#9F2E45',
    accentPrimary: '#E11D48',
    accentHover: '#BE123C',
    accentText: '#FFFFFF',
    badgeBg: '#FFE4E6',
    badgeBorder: '#FDA4AF',
    badgeText: '#9F1239',
    affirmationBg: '#FFF1F2',
    affirmationBorder: '#FDA4AF',
    affirmationText: '#881337',
    affirmationLabel: '#E11D48',
    quoteBg: '#FFF5F6',
    quoteBorder: '#FECDD3',
    quoteText: '#4C0519',
    quoteLabel: '#E11D48',
    practiceBg: '#FFE4E6',
    practiceBorder: '#FDA4AF',
    modalOverlay: 'rgba(30, 6, 11, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#E11D48',
    tabActiveBg: '#E11D48',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#FFE4E6',
    tabInactiveText: '#9F1239',
  },

  ruby_dark: {
    id: 'ruby_dark',
    name: 'Imperial Crimson',
    family: 'red',
    familyName: 'Red & Crimson',
    variant: 'dark',
    icon: '🍷',
    swatchCanvas: '#160408',
    swatchCard: '#240A10',
    swatchAccent: '#FB7185',
    subtitle: 'Luminous glowing garnet & velvety crimson',
    canvas: '#160408',
    topBar: '#1E070D',
    topBarBorder: '#3F121C',
    card: '#240A10',
    cardBorder: '#4E1624',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#19060B',
    inputBorder: '#4E1624',
    textPrimary: '#FFF1F2',
    textSecondary: '#FECDD3',
    textMuted: '#FB7185',
    accentPrimary: '#FB7185',
    accentHover: '#F43F5E',
    accentText: '#160408',
    badgeBg: '#3B0E19',
    badgeBorder: '#63182B',
    badgeText: '#FFE4E6',
    affirmationBg: '#2E0C15',
    affirmationBorder: '#63182B',
    affirmationText: '#FFF1F2',
    affirmationLabel: '#FB7185',
    quoteBg: '#21080E',
    quoteBorder: '#4E1624',
    quoteText: '#FFE4E6',
    quoteLabel: '#FB7185',
    practiceBg: '#2A0B13',
    practiceBorder: '#561626',
    modalOverlay: 'rgba(10, 2, 5, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#FB7185',
    tabActiveBg: '#FB7185',
    tabActiveText: '#160408',
    tabInactiveBg: '#2A0B13',
    tabInactiveText: '#FECDD3',
  },

  // ==========================================
  // 2. ORANGE & TERRACOTTA SPECTRUM
  // ==========================================
  amber_light: {
    id: 'amber_light',
    name: 'Warm Terracotta',
    family: 'orange',
    familyName: 'Orange & Terracotta',
    variant: 'light',
    icon: '🏺',
    swatchCanvas: '#FFF9F5',
    swatchCard: '#FFFFFF',
    swatchAccent: '#EA580C',
    subtitle: 'Vivid fiery tangerine & sunlit warmth',
    canvas: '#FFF9F5',
    topBar: '#FFFFFF',
    topBarBorder: '#FED7AA',
    card: '#FFFFFF',
    cardBorder: '#FFEDD5',
    cardShadow: 'rgba(234, 88, 12, 0.14)',
    inputBg: '#FFF7ED',
    inputBorder: '#FED7AA',
    textPrimary: '#2B1104',
    textSecondary: '#7C2D12',
    textMuted: '#9A3412',
    accentPrimary: '#EA580C',
    accentHover: '#C2410C',
    accentText: '#FFFFFF',
    badgeBg: '#FFEDD5',
    badgeBorder: '#FDBA74',
    badgeText: '#9A3412',
    affirmationBg: '#FFF7ED',
    affirmationBorder: '#FDBA74',
    affirmationText: '#7C2D12',
    affirmationLabel: '#EA580C',
    quoteBg: '#FFF9F5',
    quoteBorder: '#FED7AA',
    quoteText: '#431407',
    quoteLabel: '#EA580C',
    practiceBg: '#FFEDD5',
    practiceBorder: '#FDBA74',
    modalOverlay: 'rgba(43, 17, 4, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#EA580C',
    tabActiveBg: '#EA580C',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#FFEDD5',
    tabInactiveText: '#9A3412',
  },

  amber_dark: {
    id: 'amber_dark',
    name: 'Burnished Ochre',
    family: 'orange',
    familyName: 'Orange & Terracotta',
    variant: 'dark',
    icon: '🪵',
    swatchCanvas: '#160B04',
    swatchCard: '#261307',
    swatchAccent: '#FB923C',
    subtitle: 'Radiant glowing embers & rich teakwood',
    canvas: '#160B04',
    topBar: '#1F0F06',
    topBarBorder: '#42200D',
    card: '#261307',
    cardBorder: '#542810',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#1C0D05',
    inputBorder: '#542810',
    textPrimary: '#FFF7ED',
    textSecondary: '#FED7AA',
    textMuted: '#FB923C',
    accentPrimary: '#FB923C',
    accentHover: '#F97316',
    accentText: '#160B04',
    badgeBg: '#421E09',
    badgeBorder: '#6C310F',
    badgeText: '#FED7AA',
    affirmationBg: '#301809',
    affirmationBorder: '#6C310F',
    affirmationText: '#FFF7ED',
    affirmationLabel: '#FB923C',
    quoteBg: '#211006',
    quoteBorder: '#542810',
    quoteText: '#FFEDD5',
    quoteLabel: '#FB923C',
    practiceBg: '#2B1508',
    practiceBorder: '#5F2D13',
    modalOverlay: 'rgba(10, 4, 2, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#FB923C',
    tabActiveBg: '#FB923C',
    tabActiveText: '#160B04',
    tabInactiveBg: '#2F1709',
    tabInactiveText: '#FED7AA',
  },

  // ==========================================
  // 3. GOLD & AMBER SPECTRUM
  // ==========================================
  gold_light: {
    id: 'gold_light',
    name: 'Golden Sand',
    family: 'yellow',
    familyName: 'Gold & Amber',
    variant: 'light',
    icon: '🌾',
    swatchCanvas: '#FEFDF5',
    swatchCard: '#FFFFFF',
    swatchAccent: '#D97706',
    subtitle: 'Pure liquid gold & bright honey amber',
    canvas: '#FEFDF5',
    topBar: '#FFFFFF',
    topBarBorder: '#FDE68A',
    card: '#FFFFFF',
    cardBorder: '#FEF3C7',
    cardShadow: 'rgba(217, 119, 6, 0.14)',
    inputBg: '#FFFBEB',
    inputBorder: '#FDE68A',
    textPrimary: '#261603',
    textSecondary: '#78350F',
    textMuted: '#92400E',
    accentPrimary: '#D97706',
    accentHover: '#B45309',
    accentText: '#FFFFFF',
    badgeBg: '#FEF3C7',
    badgeBorder: '#FCD34D',
    badgeText: '#92400E',
    affirmationBg: '#FFFBEB',
    affirmationBorder: '#FCD34D',
    affirmationText: '#78350F',
    affirmationLabel: '#D97706',
    quoteBg: '#FEFDF5',
    quoteBorder: '#FDE68A',
    quoteText: '#451A03',
    quoteLabel: '#D97706',
    practiceBg: '#FEF3C7',
    practiceBorder: '#FCD34D',
    modalOverlay: 'rgba(38, 22, 3, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#D97706',
    tabActiveBg: '#D97706',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#FEF3C7',
    tabInactiveText: '#92400E',
  },

  gold_dark: {
    id: 'gold_dark',
    name: 'Golden Obsidian',
    family: 'yellow',
    familyName: 'Gold & Amber',
    variant: 'dark',
    icon: '🪙',
    swatchCanvas: '#141004',
    swatchCard: '#241B07',
    swatchAccent: '#FBBF24',
    subtitle: 'Gleaming 24k gold against smoky obsidian',
    canvas: '#141004',
    topBar: '#1C1506',
    topBarBorder: '#3C2E0B',
    card: '#241B07',
    cardBorder: '#4E3A0E',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#1A1305',
    inputBorder: '#4E3A0E',
    textPrimary: '#FFFBEB',
    textSecondary: '#FDE68A',
    textMuted: '#FBBF24',
    accentPrimary: '#FBBF24',
    accentHover: '#F59E0B',
    accentText: '#141004',
    badgeBg: '#3C2E0B',
    badgeBorder: '#614B12',
    badgeText: '#FEF3C7',
    affirmationBg: '#2E2209',
    affirmationBorder: '#614B12',
    affirmationText: '#FFFBEB',
    affirmationLabel: '#FBBF24',
    quoteBg: '#1E1706',
    quoteBorder: '#4E3A0E',
    quoteText: '#FEF3C7',
    quoteLabel: '#FBBF24',
    practiceBg: '#281E08',
    practiceBorder: '#56410F',
    modalOverlay: 'rgba(10, 8, 2, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#FBBF24',
    tabActiveBg: '#FBBF24',
    tabActiveText: '#141004',
    tabInactiveBg: '#2D2109',
    tabInactiveText: '#FDE68A',
  },

  // ==========================================
  // 4. SAGE & EMERALD SPECTRUM
  // ==========================================
  sage_light: {
    id: 'sage_light',
    name: 'Gentle Sage',
    family: 'green',
    familyName: 'Sage & Emerald',
    variant: 'light',
    icon: '🌿',
    swatchCanvas: '#F0FDF4',
    swatchCard: '#FFFFFF',
    swatchAccent: '#059669',
    subtitle: 'Vivid emerald botanical & fresh spring mint',
    canvas: '#F0FDF4',
    topBar: '#FFFFFF',
    topBarBorder: '#BBF7D0',
    card: '#FFFFFF',
    cardBorder: '#DCFCE7',
    cardShadow: 'rgba(5, 150, 105, 0.14)',
    inputBg: '#F0FDF4',
    inputBorder: '#BBF7D0',
    textPrimary: '#052E16',
    textSecondary: '#166534',
    textMuted: '#15803D',
    accentPrimary: '#059669',
    accentHover: '#047857',
    accentText: '#FFFFFF',
    badgeBg: '#DCFCE7',
    badgeBorder: '#86EFAC',
    badgeText: '#14532D',
    affirmationBg: '#F0FDF4',
    affirmationBorder: '#86EFAC',
    affirmationText: '#14532D',
    affirmationLabel: '#059669',
    quoteBg: '#F7FEE7',
    quoteBorder: '#BBF7D0',
    quoteText: '#064E3B',
    quoteLabel: '#059669',
    practiceBg: '#DCFCE7',
    practiceBorder: '#86EFAC',
    modalOverlay: 'rgba(5, 46, 22, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#059669',
    tabActiveBg: '#059669',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#DCFCE7',
    tabInactiveText: '#166534',
  },

  sage_dark: {
    id: 'sage_dark',
    name: 'Deep Forest',
    family: 'green',
    familyName: 'Sage & Emerald',
    variant: 'dark',
    icon: '🌲',
    swatchCanvas: '#05140B',
    swatchCard: '#0C2415',
    swatchAccent: '#34D399',
    subtitle: 'Luminous neon mint & deep pine canopy',
    canvas: '#05140B',
    topBar: '#0A1C11',
    topBarBorder: '#143C24',
    card: '#0C2415',
    cardBorder: '#1A4D2E',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#081A0F',
    inputBorder: '#1A4D2E',
    textPrimary: '#F0FDF4',
    textSecondary: '#86EFAC',
    textMuted: '#34D399',
    accentPrimary: '#34D399',
    accentHover: '#10B981',
    accentText: '#05140B',
    badgeBg: '#143C24',
    badgeBorder: '#1E5C37',
    badgeText: '#DCFCE7',
    affirmationBg: '#0E2E1B',
    affirmationBorder: '#1E5C37',
    affirmationText: '#F0FDF4',
    affirmationLabel: '#34D399',
    quoteBg: '#091E12',
    quoteBorder: '#1A4D2E',
    quoteText: '#DCFCE7',
    quoteLabel: '#34D399',
    practiceBg: '#0E2818',
    practiceBorder: '#205534',
    modalOverlay: 'rgba(2, 10, 5, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#34D399',
    tabActiveBg: '#34D399',
    tabActiveText: '#05140B',
    tabInactiveBg: '#133320',
    tabInactiveText: '#86EFAC',
  },

  // ==========================================
  // 5. TEAL & SEAFOAM SPECTRUM
  // ==========================================
  teal_light: {
    id: 'teal_light',
    name: 'Aquamarine Mist',
    family: 'teal',
    familyName: 'Teal & Seafoam',
    variant: 'light',
    icon: '🌊',
    swatchCanvas: '#F0FDFA',
    swatchCard: '#FFFFFF',
    swatchAccent: '#0D9488',
    subtitle: 'Brilliant jewel lagoon & crystal seafoam',
    canvas: '#F0FDFA',
    topBar: '#FFFFFF',
    topBarBorder: '#99F6E4',
    card: '#FFFFFF',
    cardBorder: '#CCFBF1',
    cardShadow: 'rgba(13, 148, 136, 0.14)',
    inputBg: '#F0FDFA',
    inputBorder: '#99F6E4',
    textPrimary: '#042F2E',
    textSecondary: '#115E59',
    textMuted: '#0F766E',
    accentPrimary: '#0D9488',
    accentHover: '#0F766E',
    accentText: '#FFFFFF',
    badgeBg: '#CCFBF1',
    badgeBorder: '#5EEAD4',
    badgeText: '#134E4A',
    affirmationBg: '#F0FDFA',
    affirmationBorder: '#5EEAD4',
    affirmationText: '#134E4A',
    affirmationLabel: '#0D9488',
    quoteBg: '#F0FDFA',
    quoteBorder: '#99F6E4',
    quoteText: '#042F2E',
    quoteLabel: '#0D9488',
    practiceBg: '#CCFBF1',
    practiceBorder: '#5EEAD4',
    modalOverlay: 'rgba(4, 47, 46, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#0D9488',
    tabActiveBg: '#0D9488',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#CCFBF1',
    tabInactiveText: '#115E59',
  },

  teal_dark: {
    id: 'teal_dark',
    name: 'Abyssal Teal',
    family: 'teal',
    familyName: 'Teal & Seafoam',
    variant: 'dark',
    icon: '🐬',
    swatchCanvas: '#041416',
    swatchCard: '#0A262A',
    swatchAccent: '#2DD4BF',
    subtitle: 'Electric glowing turquoise & maritime depths',
    canvas: '#041416',
    topBar: '#081D20',
    topBarBorder: '#103F45',
    card: '#0A262A',
    cardBorder: '#165158',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#061A1D',
    inputBorder: '#165158',
    textPrimary: '#F0FDFA',
    textSecondary: '#99F6E4',
    textMuted: '#2DD4BF',
    accentPrimary: '#2DD4BF',
    accentHover: '#14B8A6',
    accentText: '#041416',
    badgeBg: '#103F45',
    badgeBorder: '#1A616A',
    badgeText: '#CCFBF1',
    affirmationBg: '#0D3035',
    affirmationBorder: '#1A616A',
    affirmationText: '#F0FDFA',
    affirmationLabel: '#2DD4BF',
    quoteBg: '#071F22',
    quoteBorder: '#165158',
    quoteText: '#CCFBF1',
    quoteLabel: '#2DD4BF',
    practiceBg: '#0B292D',
    practiceBorder: '#1B5B63',
    modalOverlay: 'rgba(2, 10, 11, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#2DD4BF',
    tabActiveBg: '#2DD4BF',
    tabActiveText: '#041416',
    tabInactiveBg: '#10353A',
    tabInactiveText: '#99F6E4',
  },

  // ==========================================
  // 6. BLUE & OCEAN SPECTRUM
  // ==========================================
  mist: {
    id: 'mist',
    name: 'Blue Skies',
    family: 'blue',
    familyName: 'Ocean & Sky',
    variant: 'light',
    icon: '🌊',
    swatchCanvas: '#F0F7FF',
    swatchCard: '#FFFFFF',
    swatchAccent: '#2563EB',
    subtitle: 'Vivid cerulean sky & crisp coastal breeze',
    canvas: '#F0F7FF',
    topBar: '#FFFFFF',
    topBarBorder: '#BFDBFE',
    card: '#FFFFFF',
    cardBorder: '#DBEAFE',
    cardShadow: 'rgba(37, 99, 235, 0.14)',
    inputBg: '#EFF6FF',
    inputBorder: '#BFDBFE',
    textPrimary: '#0F172A',
    textSecondary: '#1E40AF',
    textMuted: '#2563EB',
    accentPrimary: '#2563EB',
    accentHover: '#1D4ED8',
    accentText: '#FFFFFF',
    badgeBg: '#DBEAFE',
    badgeBorder: '#93C5FD',
    badgeText: '#1E3A8A',
    affirmationBg: '#EFF6FF',
    affirmationBorder: '#93C5FD',
    affirmationText: '#1E3A8A',
    affirmationLabel: '#2563EB',
    quoteBg: '#F0F7FF',
    quoteBorder: '#BFDBFE',
    quoteText: '#0F172A',
    quoteLabel: '#2563EB',
    practiceBg: '#DBEAFE',
    practiceBorder: '#93C5FD',
    modalOverlay: 'rgba(15, 23, 42, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#2563EB',
    tabActiveBg: '#2563EB',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#DBEAFE',
    tabInactiveText: '#1E40AF',
  },

  deep_sea: {
    id: 'deep_sea',
    name: 'Deep Sea',
    family: 'blue',
    familyName: 'Ocean & Sky',
    variant: 'dark',
    icon: '🐋',
    swatchCanvas: '#09101D',
    swatchCard: '#101F38',
    swatchAccent: '#38BDF8',
    subtitle: 'Electric neon sky pop & midnight ocean depths',
    canvas: '#09101D',
    topBar: '#0C182B',
    topBarBorder: '#183259',
    card: '#101F38',
    cardBorder: '#204172',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#0D192E',
    inputBorder: '#204172',
    textPrimary: '#F8FAFC',
    textSecondary: '#93C5FD',
    textMuted: '#38BDF8',
    accentPrimary: '#38BDF8',
    accentHover: '#0EA5E9',
    accentText: '#09101D',
    badgeBg: '#183259',
    badgeBorder: '#254E8A',
    badgeText: '#DBEAFE',
    affirmationBg: '#132644',
    affirmationBorder: '#254E8A',
    affirmationText: '#F8FAFC',
    affirmationLabel: '#38BDF8',
    quoteBg: '#0C1A30',
    quoteBorder: '#204172',
    quoteText: '#DBEAFE',
    quoteLabel: '#38BDF8',
    practiceBg: '#12233E',
    practiceBorder: '#25477B',
    modalOverlay: 'rgba(4, 7, 13, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#38BDF8',
    tabActiveBg: '#38BDF8',
    tabActiveText: '#09101D',
    tabInactiveBg: '#152948',
    tabInactiveText: '#93C5FD',
  },

  // ==========================================
  // 7. INDIGO & TWILIGHT SPECTRUM
  // ==========================================
  indigo_light: {
    id: 'indigo_light',
    name: 'Twilight Breeze',
    family: 'indigo',
    familyName: 'Indigo & Twilight',
    variant: 'light',
    icon: '🌌',
    swatchCanvas: '#F5F3FF',
    swatchCard: '#FFFFFF',
    swatchAccent: '#4F46E5',
    subtitle: 'Vivid royal periwinkle & energetic twilight',
    canvas: '#F5F3FF',
    topBar: '#FFFFFF',
    topBarBorder: '#C7D2FE',
    card: '#FFFFFF',
    cardBorder: '#E0E7FF',
    cardShadow: 'rgba(79, 70, 229, 0.14)',
    inputBg: '#EEF2FF',
    inputBorder: '#C7D2FE',
    textPrimary: '#1E1B4B',
    textSecondary: '#3730A3',
    textMuted: '#4F46E5',
    accentPrimary: '#4F46E5',
    accentHover: '#4338CA',
    accentText: '#FFFFFF',
    badgeBg: '#E0E7FF',
    badgeBorder: '#A5B4FC',
    badgeText: '#312E81',
    affirmationBg: '#EEF2FF',
    affirmationBorder: '#A5B4FC',
    affirmationText: '#312E81',
    affirmationLabel: '#4F46E5',
    quoteBg: '#F5F3FF',
    quoteBorder: '#C7D2FE',
    quoteText: '#1E1B4B',
    quoteLabel: '#4F46E5',
    practiceBg: '#E0E7FF',
    practiceBorder: '#A5B4FC',
    modalOverlay: 'rgba(30, 27, 75, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#4F46E5',
    tabActiveBg: '#4F46E5',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#E0E7FF',
    tabInactiveText: '#3730A3',
  },

  indigo_dark: {
    id: 'indigo_dark',
    name: 'Midnight Indigo',
    family: 'indigo',
    familyName: 'Indigo & Twilight',
    variant: 'dark',
    icon: '🌙',
    swatchCanvas: '#0A091A',
    swatchCard: '#151336',
    swatchAccent: '#818CF8',
    subtitle: 'Luminous electric violet & deep celestial night',
    canvas: '#0A091A',
    topBar: '#0E0D24',
    topBarBorder: '#1F1B4E',
    card: '#151336',
    cardBorder: '#2D2770',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#100E2B',
    inputBorder: '#2D2770',
    textPrimary: '#F5F3FF',
    textSecondary: '#C7D2FE',
    textMuted: '#818CF8',
    accentPrimary: '#818CF8',
    accentHover: '#6366F1',
    accentText: '#0A091A',
    badgeBg: '#1F1B4E',
    badgeBorder: '#352E84',
    badgeText: '#E0E7FF',
    affirmationBg: '#191741',
    affirmationBorder: '#352E84',
    affirmationText: '#F5F3FF',
    affirmationLabel: '#818CF8',
    quoteBg: '#100F29',
    quoteBorder: '#2D2770',
    quoteText: '#E0E7FF',
    quoteLabel: '#818CF8',
    practiceBg: '#17143D',
    practiceBorder: '#302A79',
    modalOverlay: 'rgba(4, 4, 10, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#818CF8',
    tabActiveBg: '#818CF8',
    tabActiveText: '#0A091A',
    tabInactiveBg: '#1B1846',
    tabInactiveText: '#C7D2FE',
  },

  // ==========================================
  // 8. PURPLE & LAVENDER SPECTRUM
  // ==========================================
  lavender_light: {
    id: 'lavender_light',
    name: 'Lavender Dawn',
    family: 'purple',
    familyName: 'Lavender & Violet',
    variant: 'light',
    icon: '🪻',
    swatchCanvas: '#FAF5FF',
    swatchCard: '#FFFFFF',
    swatchAccent: '#7C3AED',
    subtitle: 'Vibrant amethyst violet & radiant orchid mist',
    canvas: '#FAF5FF',
    topBar: '#FFFFFF',
    topBarBorder: '#E9D5FF',
    card: '#FFFFFF',
    cardBorder: '#F3E8FF',
    cardShadow: 'rgba(124, 58, 237, 0.14)',
    inputBg: '#FAF5FF',
    inputBorder: '#E9D5FF',
    textPrimary: '#2E1065',
    textSecondary: '#6B21A8',
    textMuted: '#7E22CE',
    accentPrimary: '#7C3AED',
    accentHover: '#6D28D9',
    accentText: '#FFFFFF',
    badgeBg: '#F3E8FF',
    badgeBorder: '#D8B4FE',
    badgeText: '#581C87',
    affirmationBg: '#FAF5FF',
    affirmationBorder: '#D8B4FE',
    affirmationText: '#581C87',
    affirmationLabel: '#7C3AED',
    quoteBg: '#FAF5FF',
    quoteBorder: '#E9D5FF',
    quoteText: '#2E1065',
    quoteLabel: '#7C3AED',
    practiceBg: '#F3E8FF',
    practiceBorder: '#D8B4FE',
    modalOverlay: 'rgba(46, 16, 101, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#7C3AED',
    tabActiveBg: '#7C3AED',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#F3E8FF',
    tabInactiveText: '#6B21A8',
  },

  lavender_dark: {
    id: 'lavender_dark',
    name: 'Deep Amethyst',
    family: 'purple',
    familyName: 'Lavender & Violet',
    variant: 'dark',
    icon: '🔮',
    swatchCanvas: '#110721',
    swatchCard: '#220E42',
    swatchAccent: '#C084FC',
    subtitle: 'Luminous neon purple pop & royal shadows',
    canvas: '#110721',
    topBar: '#180A2E',
    topBarBorder: '#351664',
    card: '#220E42',
    cardBorder: '#481F87',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#1A0B33',
    inputBorder: '#481F87',
    textPrimary: '#FAF5FF',
    textSecondary: '#E9D5FF',
    textMuted: '#C084FC',
    accentPrimary: '#C084FC',
    accentHover: '#A855F7',
    accentText: '#110721',
    badgeBg: '#351664',
    badgeBorder: '#5624A2',
    badgeText: '#F3E8FF',
    affirmationBg: '#2A1252',
    affirmationBorder: '#5624A2',
    affirmationText: '#FAF5FF',
    affirmationLabel: '#C084FC',
    quoteBg: '#1C0C37',
    quoteBorder: '#481F87',
    quoteText: '#F3E8FF',
    quoteLabel: '#C084FC',
    practiceBg: '#260F4A',
    practiceBorder: '#502094',
    modalOverlay: 'rgba(6, 2, 12, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#C084FC',
    tabActiveBg: '#C084FC',
    tabActiveText: '#110721',
    tabInactiveBg: '#2C1355',
    tabInactiveText: '#E9D5FF',
  },

  // ==========================================
  // 9. ROSE & BLUSH SPECTRUM
  // ==========================================
  rose_light: {
    id: 'rose_light',
    name: 'Blush Rose',
    family: 'rose',
    familyName: 'Rose & Blush',
    variant: 'light',
    icon: '🌸',
    swatchCanvas: '#FFF1F2',
    swatchCard: '#FFFFFF',
    swatchAccent: '#F43F5E',
    subtitle: 'Vivid cherry blossom rose & radiant petal energy',
    canvas: '#FFF1F2',
    topBar: '#FFFFFF',
    topBarBorder: '#FECDD3',
    card: '#FFFFFF',
    cardBorder: '#FFE4E6',
    cardShadow: 'rgba(244, 63, 94, 0.14)',
    inputBg: '#FFF1F2',
    inputBorder: '#FECDD3',
    textPrimary: '#350613',
    textSecondary: '#881337',
    textMuted: '#BE123C',
    accentPrimary: '#F43F5E',
    accentHover: '#E11D48',
    accentText: '#FFFFFF',
    badgeBg: '#FFE4E6',
    badgeBorder: '#FDA4AF',
    badgeText: '#9F1239',
    affirmationBg: '#FFF1F2',
    affirmationBorder: '#FDA4AF',
    affirmationText: '#881337',
    affirmationLabel: '#F43F5E',
    quoteBg: '#FFF1F2',
    quoteBorder: '#FECDD3',
    quoteText: '#4C0519',
    quoteLabel: '#F43F5E',
    practiceBg: '#FFE4E6',
    practiceBorder: '#FDA4AF',
    modalOverlay: 'rgba(53, 6, 19, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#F43F5E',
    tabActiveBg: '#F43F5E',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#FFE4E6',
    tabInactiveText: '#881337',
  },

  rose_dark: {
    id: 'rose_dark',
    name: 'Midnight Wine',
    family: 'rose',
    familyName: 'Rose & Blush',
    variant: 'dark',
    icon: '🍷',
    swatchCanvas: '#180510',
    swatchCard: '#2B0A1D',
    swatchAccent: '#FB7185',
    subtitle: 'Luminous hot pink pop & velvety plum crimson',
    canvas: '#180510',
    topBar: '#210717',
    topBarBorder: '#45102F',
    card: '#2B0A1D',
    cardBorder: '#5E1740',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#1E0714',
    inputBorder: '#5E1740',
    textPrimary: '#FFF1F2',
    textSecondary: '#FECDD3',
    textMuted: '#FB7185',
    accentPrimary: '#FB7185',
    accentHover: '#F43F5E',
    accentText: '#180510',
    badgeBg: '#45102F',
    badgeBorder: '#721B4F',
    badgeText: '#FFE4E6',
    affirmationBg: '#350D24',
    affirmationBorder: '#721B4F',
    affirmationText: '#FFF1F2',
    affirmationLabel: '#FB7185',
    quoteBg: '#240819',
    quoteBorder: '#5E1740',
    quoteText: '#FFE4E6',
    quoteLabel: '#FB7185',
    practiceBg: '#2E0B20',
    practiceBorder: '#691848',
    modalOverlay: 'rgba(10, 2, 7, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#FB7185',
    tabActiveBg: '#FB7185',
    tabActiveText: '#180510',
    tabInactiveBg: '#330C23',
    tabInactiveText: '#FECDD3',
  },

  // ==========================================
  // 10. EARTH & SAND SPECTRUM
  // ==========================================
  linen: {
    id: 'linen',
    name: 'Warm Linen',
    family: 'earth',
    familyName: 'Earth & Sand',
    variant: 'light',
    icon: '🌾',
    swatchCanvas: '#FAF7F0',
    swatchCard: '#FFFFFF',
    swatchAccent: '#B45309',
    subtitle: 'Rich burnished copper & tactile flax warmth',
    canvas: '#FAF7F0',
    topBar: '#FFFFFF',
    topBarBorder: '#E6DCBF',
    card: '#FFFFFF',
    cardBorder: '#F0E8D0',
    cardShadow: 'rgba(180, 83, 9, 0.14)',
    inputBg: '#F5EFE0',
    inputBorder: '#E0D4B2',
    textPrimary: '#2B1E0C',
    textSecondary: '#6B4D20',
    textMuted: '#8D6628',
    accentPrimary: '#B45309',
    accentHover: '#92400E',
    accentText: '#FFFFFF',
    badgeBg: '#EFE7CF',
    badgeBorder: '#D8C79B',
    badgeText: '#593F16',
    affirmationBg: '#F6F0DF',
    affirmationBorder: '#D8C79B',
    affirmationText: '#593F16',
    affirmationLabel: '#B45309',
    quoteBg: '#FAF7F0',
    quoteBorder: '#E6DCBF',
    quoteText: '#2B1E0C',
    quoteLabel: '#B45309',
    practiceBg: '#EFE7CF',
    practiceBorder: '#D8C79B',
    modalOverlay: 'rgba(43, 30, 12, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#B45309',
    tabActiveBg: '#B45309',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#EFE7CF',
    tabInactiveText: '#6B4D20',
  },

  earth_dark: {
    id: 'earth_dark',
    name: 'Espresso & Earth',
    family: 'earth',
    familyName: 'Earth & Sand',
    variant: 'dark',
    icon: '🪵',
    swatchCanvas: '#140E0A',
    swatchCard: '#271B14',
    swatchAccent: '#E0A96D',
    subtitle: 'Luminous terracotta gold & dark roasted espresso',
    canvas: '#140E0A',
    topBar: '#1D140F',
    topBarBorder: '#3C291E',
    card: '#271B14',
    cardBorder: '#4C3426',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#1B130E',
    inputBorder: '#4C3426',
    textPrimary: '#FFF8F0',
    textSecondary: '#F2D7BF',
    textMuted: '#E0A96D',
    accentPrimary: '#E0A96D',
    accentHover: '#C98F4F',
    accentText: '#140E0A',
    badgeBg: '#3C291E',
    badgeBorder: '#5F4130',
    badgeText: '#F7E7DA',
    affirmationBg: '#302219',
    affirmationBorder: '#5F4130',
    affirmationText: '#FFF8F0',
    affirmationLabel: '#E0A96D',
    quoteBg: '#211711',
    quoteBorder: '#4C3426',
    quoteText: '#F7E7DA',
    quoteLabel: '#E0A96D',
    practiceBg: '#2B1E16',
    practiceBorder: '#553A2B',
    modalOverlay: 'rgba(10, 7, 5, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#E0A96D',
    tabActiveBg: '#E0A96D',
    tabActiveText: '#140E0A',
    tabInactiveBg: '#2E2017',
    tabInactiveText: '#F2D7BF',
  },

  // ==========================================
  // 11. SLATE & NEUTRAL SPECTRUM
  // ==========================================
  slate_light: {
    id: 'slate_light',
    name: 'Morning Mist',
    family: 'neutral',
    familyName: 'Slate & Charcoal',
    variant: 'light',
    icon: '🪨',
    swatchCanvas: '#F8FAFC',
    swatchCard: '#FFFFFF',
    swatchAccent: '#0284C7',
    subtitle: 'Pristine modern slate white & electric cyan pop',
    canvas: '#F8FAFC',
    topBar: '#FFFFFF',
    topBarBorder: '#E2E8F0',
    card: '#FFFFFF',
    cardBorder: '#E2E8F0',
    cardShadow: 'rgba(2, 132, 199, 0.12)',
    inputBg: '#F1F5F9',
    inputBorder: '#CBD5E1',
    textPrimary: '#0F172A',
    textSecondary: '#334155',
    textMuted: '#64748B',
    accentPrimary: '#0284C7',
    accentHover: '#0369A1',
    accentText: '#FFFFFF',
    badgeBg: '#E0F2FE',
    badgeBorder: '#BAE6FD',
    badgeText: '#0369A1',
    affirmationBg: '#F0F9FF',
    affirmationBorder: '#BAE6FD',
    affirmationText: '#0369A1',
    affirmationLabel: '#0284C7',
    quoteBg: '#F8FAFC',
    quoteBorder: '#E2E8F0',
    quoteText: '#0F172A',
    quoteLabel: '#0284C7',
    practiceBg: '#E0F2FE',
    practiceBorder: '#BAE6FD',
    modalOverlay: 'rgba(15, 23, 42, 0.68)',
    crisisBg: '#FFF1F2',
    crisisBorder: '#FDA4AF',
    crisisText: '#9F1239',
    crisisAccent: '#0284C7',
    tabActiveBg: '#0284C7',
    tabActiveText: '#FFFFFF',
    tabInactiveBg: '#E2E8F0',
    tabInactiveText: '#334155',
  },

  dusk: {
    id: 'dusk',
    name: 'Charcoal Dusk',
    family: 'neutral',
    familyName: 'Slate & Charcoal',
    variant: 'dark',
    icon: '🌘',
    swatchCanvas: '#0A0E17',
    swatchCard: '#151D2C',
    swatchAccent: '#38BDF8',
    subtitle: 'Glowing electric cyan pop & sleek deep carbon',
    canvas: '#0A0E17',
    topBar: '#0F1624',
    topBarBorder: '#1F2B40',
    card: '#151D2C',
    cardBorder: '#283852',
    cardShadow: 'rgba(0, 0, 0, 0.55)',
    inputBg: '#101622',
    inputBorder: '#283852',
    textPrimary: '#F8FAFC',
    textSecondary: '#CBD5E1',
    textMuted: '#38BDF8',
    accentPrimary: '#38BDF8',
    accentHover: '#0EA5E9',
    accentText: '#0A0E17',
    badgeBg: '#1F2B40',
    badgeBorder: '#2E3F5E',
    badgeText: '#E2E8F0',
    affirmationBg: '#192336',
    affirmationBorder: '#2E3F5E',
    affirmationText: '#F8FAFC',
    affirmationLabel: '#38BDF8',
    quoteBg: '#111723',
    quoteBorder: '#283852',
    quoteText: '#E2E8F0',
    quoteLabel: '#38BDF8',
    practiceBg: '#1A2333',
    practiceBorder: '#2B3B56',
    modalOverlay: 'rgba(5, 7, 12, 0.75)',
    crisisBg: '#3B0E19',
    crisisBorder: '#63182B',
    crisisText: '#FECDD3',
    crisisAccent: '#38BDF8',
    tabActiveBg: '#38BDF8',
    tabActiveText: '#0A0E17',
    tabInactiveBg: '#1B2538',
    tabInactiveText: '#CBD5E1',
  },
};

// Aliases for backwards compatibility
(THEMES as any).sage = THEMES.sage_light;
(THEMES as any).clay = THEMES.rose_light;
(THEMES as any).ocean_light = THEMES.mist;
(THEMES as any).ocean_dark = THEMES.deep_sea;

export const THEME_LIST: ThemePalette[] = [
  // Red
  THEMES.ruby_light,
  THEMES.ruby_dark,
  // Orange
  THEMES.amber_light,
  THEMES.amber_dark,
  // Yellow
  THEMES.gold_light,
  THEMES.gold_dark,
  // Green
  THEMES.sage_light,
  THEMES.sage_dark,
  // Teal
  THEMES.teal_light,
  THEMES.teal_dark,
  // Blue
  THEMES.mist,
  THEMES.deep_sea,
  // Indigo
  THEMES.indigo_light,
  THEMES.indigo_dark,
  // Purple
  THEMES.lavender_light,
  THEMES.lavender_dark,
  // Rose
  THEMES.rose_light,
  THEMES.rose_dark,
  // Earth
  THEMES.linen,
  THEMES.earth_dark,
  // Neutral
  THEMES.slate_light,
  THEMES.dusk,
];

interface ThemeContextType {
  themeMode: ThemeMode;
  theme: ThemePalette;
  setThemeMode: (mode: ThemeMode) => void;
}

const ThemeContext = createContext<ThemeContextType>({
  themeMode: 'mist',
  theme: THEMES.mist,
  setThemeMode: () => {},
});

const THEME_STORAGE_KEY = 'inner_compass_theme_mode_v2';

export const ThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [themeMode, setThemeModeState] = useState<ThemeMode>(() => {
    try {
      if (typeof localStorage !== 'undefined') {
        const stored = localStorage.getItem(THEME_STORAGE_KEY) as string;
        if (stored === 'sage') return 'sage_light';
        if (stored === 'clay') return 'rose_light';
        if (stored && (THEMES as any)[stored]) {
          return stored as ThemeMode;
        }
      }
    } catch {
      // fallback to mist
    }
    return 'mist';
  });

  const setThemeMode = (mode: ThemeMode) => {
    setThemeModeState(mode);
    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem(THEME_STORAGE_KEY, mode);
      }
    } catch {
      // ignore
    }
  };

  const theme = THEMES[themeMode] || THEMES.mist;

  // Apply theme canvas to document body to prevent white flashes or margins
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.body.style.backgroundColor = theme.canvas;
      document.body.style.color = theme.textPrimary;
    }
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ themeMode, theme, setThemeMode }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = (): ThemeContextType => {
  return useContext(ThemeContext);
};
